#!/bin/sh
# Shows my cpu usage for dwmblocks

USAGE=$(top -bn1 | grep "Cpu(s)" | \
    sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
    awk '{print 100 - $1}')

NUM=$USAGE

LEN=${#NUM}

if [ $LEN -eq 5 ]; then
    echo "[⚡:  $NUM%]"
elif [ $LEN -eq 4 ]; then
    echo "[⚡:   $NUM%]"
elif [ $LEN -eq 3 ]; then
    echo "[⚡:    $NUM%]"
elif [ $LEN -eq 2 ]; then
    echo "[⚡:     $NUM%]"
elif [ $LEN -eq 1 ]; then
    echo "[⚡:      $NUM%]"
else
    echo "[⚡: $NUM%]"
fi
