#!/bin/sh
# Shows my cpu usage for dwmblocks

USAGE=$(top -bn1 | grep "Cpu(s)" | \
    sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
    awk '{print 100 - $1}')

NUM=$(echo "$USAGE" | sed "s/\..*//")

echo "[C $NUM%]"
