#!/bin/sh
echo -e "\033[94m\033[1mwm       \033[0m\033[90mdwm"
echo -e "\033[94m\033[1mos       \033[0m\033[90mblue dorito distro"
echo -e "\033[94m\033[1mfont     \033[0m\033[90mfira mono"
echo -e "\033[94m\033[1mshell    \033[0m\033[90mfish"
echo -e "\033[94m\033[1mkernel   \033[0m\033[90mlinux 5.8.3"
echo -e "\033[94m\033[1meditor   \033[0m\033[90mneovim"
echo -e "\033[94m\033[1muptime   \033[0m\033[90mforever"
echo -e "\033[94m\033[1mmeme-ry  \033[0m\033[90m1024T"
echo -e "\033[94m\033[1mterminal \033[0m\033[90mst"
f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'
 
 
cat << EOF
 
 $f1███$d▄$t  $f2███$d▄$t  $f3███$d▄$t  $f4███$d▄$t  $f5███$d▄$t  $f6███$d▄$t  $f7███$d▄$t  
 $f1███$d█$t  $f2███$d█$t  $f3███$d█$t  $f4███$d█$t  $f5███$d█$t  $f6███$d█$t  $f7███$d█$t  
 $f1███$d█$t  $f2███$d█$t  $f3███$d█$t  $f4███$d█$t  $f5███$d█$t  $f6███$d█$t  $f7███$d█$t  
 $d$f1 ▀▀▀   $f2▀▀▀   $f3▀▀▀   $f4▀▀▀   $f5▀▀▀   $f6▀▀▀   $f7▀▀▀  
EOF
