#!/bin/sh
# licensed under the Unlicense
# TODO:
# - module files

set -e

die() {
	>&2 printf "%s\n" "$*"
	exit 1
}

[ "$(id -u)" = 0 ] && die "do not run as root"

: "${USR_DIR:=$HOME/src/git/usr}"

mkdir -p "$USR_DIR"/var
mkdir -p "$USR_DIR"/home
mkdir -p "$USR_DIR"/modules

usage() {
	die "usage: usr <option [arg]> 

options:
  -a <module>  add module
  -r <module>  remove module
  -i <module>  module information
  -g <module>  get module
  -u           update remote
  -l           list local modules
  -li          list installed modules
  -lr          list remote modules"
}

module_add() {
	MOD="$2"
	MOD_FILE="$USR_DIR/modules/$MOD".mod.sh
	MOD_INSTALL="$USR_DIR/var/$MOD".installed

	[ -e "$MOD_INSTALL" ] && die "$MOD is already installed"
	[ -z "$MOD" ] && usage

	# shellcheck source=modules/test.mod.sh
	. "$MOD_FILE"

	printf "adding %s...\n" "$MOD"
	"$MOD"_add

	touch "$MOD_INSTALL"
}

module_remove() {
	MOD="$2"
	MOD_FILE="$USR_DIR/modules/$MOD".mod.sh
	MOD_INSTALL="$USR_DIR/var/$MOD".installed

	[ -e "$MOD_INSTALL" ] || die "$MOD is not installed"
	[ -z "$MOD" ] && usage

	# shellcheck source=modules/test.mod.sh
	. "$MOD_FILE"

	printf "removing %s...\n" "$MOD"
	"$MOD"_remove

	rm "$MOD_INSTALL"
}

module_info() {
	MOD="$2"
	MOD_FILE="$USR_DIR/modules/$MOD".mod.sh

	[ -z "$MOD" ] && usage

	# shellcheck source=modules/test.mod.sh
	. "$MOD_FILE"

	printf "%s:\n" "$MOD"
	"$MOD"_info
}

get_module() {
	MOD="$2"
	MOD_FILE="$USR_DIR/modules/$MOD".mod.sh

	[ -z "$MOD" ] && usage

	VALID=""
	while read -r RMOD; do 
		if [ "$MOD" = "$RMOD" ] ; then
			VALID="yes"
		fi
	done <"$USR_DIR"/var/remote.list

	[ "$VALID" = "yes" ] || die "remote does not have $MOD"

	URL=$(cat "$USR_DIR"/var/remote)
	URL="$URL"modules/"$MOD".mod.sh
	printf "getting %s\n" "$URL"
	printf "url = %s" "$URL" | curl -sLf -o "$USR_DIR/modules/$MOD".mod.sh -K - || die "error getting"
}

list_modules() {
	for MOD in "$USR_DIR"/modules/*; do 
		if [ -f "$MOD" ] ; then
			if [ "${MOD#*.}" = "mod.sh" ] ; then
				NODOT=${MOD%%.*}
				printf "%s\n" "${NODOT##*/}"
			fi
		fi
	done
}

list_installed() {
	for MOD in "$USR_DIR"/var/*; do 
		if [ -f "$MOD" ] ; then
			if [ "${MOD#*.}" = "installed" ] ; then
				NODOT=${MOD%%.*}
				printf "%s\n" "${NODOT##*/}"
			fi
		fi
	done
}

list_remote() {
	while read -r MOD; do 
		printf "%s\n" "$MOD"
	done <"$USR_DIR"/var/remote.list
}

update_remote() {
	URL=$(cat "$USR_DIR"/var/remote)
	URL="$URL"modules/mod.list
	printf "getting %s\n" "$URL"
	printf "url = %s" "$URL" | curl -sLf -o "$USR_DIR"/var/remote.list -K - || die "error updating"
}

# create module list if it does not exist
[ -e "$USR_DIR"/modules/mod.list ] || list_modules > "$USR_DIR"/modules/mod.list

# create remote URL file if it does not exist
[ -e "$USR_DIR"/var/remote ] || printf "https://raw.githubusercontent.com/tteeoo/usr/main/" > "$USR_DIR"/var/remote

case ${1#-} in
	h) usage ;;
	a) module_add "$@" ;;
	r) module_remove "$@" ;;
	i) module_info "$@" ;;
	g) get_module "$@" ;;
	l) list_modules ;;
	u) update_remote ;;
	li) list_installed ;;
	lr) list_remote ;;
	*) usage ;;
esac

exit 0
