#!/bin/sh
# Prints volume information for dwmblocks

VOL=$(amixer -D default sget Master | grep 'Mono:' | awk -F'[][]' '{ print $2 }')
if ["$VOL" -eq ""]; then
	VOL=$(amixer -D default sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }')
fi
echo "$VOL"
