#!/bin/bash

VOL=$(amixer -D default sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }')

LEN=${#VOL}

if [ $LEN -eq 3 ]; then
    echo "[🔉:  $VOL]"
elif [ $LEN -eq 2 ]; then
    echo "[🔉:   $VOL]"
else
    echo "[🔉: $VOL]"
fi

