"
" Theo Henson's vimrc
" Configuration file for vim (place at ~/.vimrc or ~/.vim/vimrc)
"

" Add some remaps for when you type too quickly
cnoremap Wq<cr> wq<cr>
cnoremap W<cr> w<cr>
cnoremap Q<cr> q<cr>

" Unmap Q to enter Ex mode
nnoremap Q <nop>

" Remaps for easier split navigation
noremap <c-h> <c-w>h
noremap <c-j> <c-w>j
noremap <c-k> <c-w>k
noremap <c-l> <c-w>l

" Easier search navigation
nnoremap n nzz
nnoremap N Nzz
set nohlsearch

" Set leader key to ,
let mapleader=','

" Disable vi compatibility
set nocompatible

" Clean up ~
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/info
set backupdir=~/.vim/cache//,.
set directory=~/.vim/cache//,.
set undodir=~/.vim/cache//,.

" Make backspace be handled nicely
set backspace=2

" Enable line numbers
set number
set relativenumber

" Change where splits open
set splitbelow splitright

" Disable wrap
set nowrap

" Show command as you type 
set showcmd

" Set defualt encoding
set encoding=UTF-8

" Indentation
set tabstop=8
set noexpandtab
set autoindent
set listchars=tab:\|\ 
set list

" Turn on wildcard menu and add to path
set wildmenu
set path+=**

" Create custom statusline
function! GitBranch()
	  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
	let l:branchname = GitBranch()
	return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction

set showmode
set laststatus=2
set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{StatuslineGit()}
set statusline+=%#LineNr#
set statusline+=\ %F
set statusline+=%m\ 
set statusline+=%r\ 
set statusline+=%h\ 
set statusline+=%=
set statusline+=%#Pmenu#
set statusline+=%y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c

" Create MakeTags command for ctags
command! MakeTags !ctags -R .
noremap <c-r> :MakeTags<cr>

" Detect filetype
filetype plugin indent on

" Set colors
syntax on
colorscheme pablo
if filereadable(expand('~/.vim/colors/gruvbox.vim'))
	colorscheme gruvbox
endif

" Enable cursorline in insert mode
autocmd InsertEnter,InsertLeave * set cul!
