"
" Theo Henson's vimrc
" Configuration file for vim (place at ~/.vimrc or ~/.vim/vimrc)
"

" Some remaps for when you type too quickly {{{
cnoremap Wq<cr> wq<cr>
cnoremap W<cr> w<cr>
cnoremap Q<cr> q<cr>
nnoremap Q <nop>
" }}}

" Keys for easier split navigation {{{
set splitbelow splitright
noremap <C-s> :split<CR>
noremap <C-v> :vsplit<CR>
noremap <C-c> <C-w>q
noremap <c-h> <c-w>h
noremap <c-j> <c-w>j
noremap <c-k> <c-w>k
noremap <c-l> <c-w>l
" }}}

" Keys for easier tab navigation {{{
noremap <A-TAB> :tabnext<CR>
noremap <A-t> :tabnew<CR>
noremap <A-c> :tabclose<CR> 
" }}}

" Folds {{{
set foldmethod=marker
" }}}

" Easier search navigation {{{
nnoremap n nzz
nnoremap N Nzz
nnoremap S :%s//g<Left><Left>
set nohlsearch
set ignorecase
" }}}

" Set leader key to comma {{{
let mapleader=','
" }}}

" General compatibility {{{
filetype plugin indent on
set nocompatible
set backspace=2
set encoding=UTF-8
" }}}

" Clean up ~ {{{
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/info
set backupdir=~/.vim/cache//,.
set directory=~/.vim/cache//,.
set undodir=~/.vim/cache//,.
" }}}

" Enable line numbers and change line wrap {{{
set number
set relativenumber
set nowrap
" }}}

" Indentation {{{
set tabstop=8
set noexpandtab
set autoindent
set listchars=tab:\|\ 
set list
" }}}

" Fuzzy file finding {{{
set wildmenu
set path+=**
noremap <C-f> :find 
" }}}

" Create custom statusline {{{
function! GitBranch()
	  return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction
function! StatuslineGit()
	let l:branchname = GitBranch()
	return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction
set showmode
set showcmd
set laststatus=2
set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{StatuslineGit()}
set statusline+=%#LineNr#
set statusline+=\ %F
set statusline+=%m\ 
set statusline+=%r\ 
set statusline+=%h\ 
set statusline+=%=
set statusline+=%#Pmenu#
set statusline+=%y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
" }}}

" Create MakeTags command for ctags {{{
command! MakeTags !ctags -R .
noremap <C-r> :MakeTags<cr>
" }}}

" Set colors {{{
syntax on
colorscheme pablo
if filereadable(expand('~/.vim/colors/gruvbox.vim'))
	colorscheme gruvbox
endif
" }}}

" Enable cursorline in insert mode {{{
autocmd InsertEnter,InsertLeave * set cul!
" }}}
